# Generated by Django 2.2.4 on 2020-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20201110_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(verbose_name='%B %d %Y'),
        ),
    ]
